### ISSUE TITLE
cargo build error: struct field shorthands are unstable (see issue #37340)

### ISSUE THREAD

**Issue by nemobis** [the8472/reapfrog#2]
With fastar f74dd0428c742e1aa454e3b954c5b84db8606fc7 , cargo 0.17.0-0ubuntu1, rustc 1.16.0+dfsg1-1~exp1ubuntu1 , Ubuntu 16.04 with Linux 4.10.0-22-generic.

```
error: struct field shorthands are unstable (see issue #37340)
  --> /home/fondazione/.cargo/registry/src/github.com-1ecc6299db9ec823/reapfrog-0.2.0/src/lib.rs:38:18
   |
38 |         Prefetch{f, read_pos: 0, length: len, p, to_drop: 0, prefetch_pos: 0}
   |                  ^

error: struct field shorthands are unstable (see issue #37340)
  --> /home/fondazione/.cargo/registry/src/github.com-1ecc6299db9ec823/reapfrog-0.2.0/src/lib.rs:38:47
   |
38 |         Prefetch{f, read_pos: 0, length: len, p, to_drop: 0, prefetch_pos: 0}
   |                                               ^

error: aborting due to 2 previous errors

error: Could not compile `reapfrog`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by nemobis** [comment]
From https://github.com/rust-lang/rfcs/pull/1682 and https://github.com/rust-lang/rust/issues/37340 I can't quite tell what one is *supposed* to do, but if I change that line to have `f: f` and `p: p` this error goes away.

**Comment by the8472** [comment]
> rustc 1.16.0

Field shorthand initializers have been in stable release [since 1.17](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1170-2017-04-27). Current stable is 1.18.

**Comment by the8472** [comment]
You can either install current cargo/rust versions via [rustup](https://www.rustup.rs/) or download a fastar binary for x64 linux from the [github releases](https://github.com/the8472/fastar/releases)
